// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

/*
Package payload is a generated protocol buffer package.

It is generated from these files:
	employee.proto
	payload.proto

It has these top-level messages:
	EmployeePayload
	Payload
*/
package payload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmployeePayload_Type int32

const (
	EmployeePayload_UNKNOWN EmployeePayload_Type = 0
)

var EmployeePayload_Type_name = map[int32]string{
	0: "UNKNOWN",
}
var EmployeePayload_Type_value = map[string]int32{
	"UNKNOWN": 0,
}

func (x EmployeePayload_Type) String() string {
	return proto.EnumName(EmployeePayload_Type_name, int32(x))
}
func (EmployeePayload_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type EmployeePayload struct {
	Type  EmployeePayload_Type `protobuf:"varint,1,opt,name=type,enum=payload.EmployeePayload_Type" json:"type,omitempty"`
	Id    string               `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Jwt   string               `protobuf:"bytes,3,opt,name=jwt" json:"jwt,omitempty"`
	Shift string               `protobuf:"bytes,4,opt,name=shift" json:"shift,omitempty"`
}

func (m *EmployeePayload) Reset()                    { *m = EmployeePayload{} }
func (m *EmployeePayload) String() string            { return proto.CompactTextString(m) }
func (*EmployeePayload) ProtoMessage()               {}
func (*EmployeePayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmployeePayload) GetType() EmployeePayload_Type {
	if m != nil {
		return m.Type
	}
	return EmployeePayload_UNKNOWN
}

func (m *EmployeePayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeePayload) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *EmployeePayload) GetShift() string {
	if m != nil {
		return m.Shift
	}
	return ""
}

func init() {
	proto.RegisterType((*EmployeePayload)(nil), "payload.EmployeePayload")
	proto.RegisterEnum("payload.EmployeePayload_Type", EmployeePayload_Type_name, EmployeePayload_Type_value)
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x2d, 0xc8,
	0xc9, 0xaf, 0x4c, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0xac, 0xcc,
	0xc9, 0x4f, 0x4c, 0x51, 0x9a, 0xc8, 0xc8, 0xc5, 0xef, 0x0a, 0x95, 0x0b, 0x80, 0x88, 0x09, 0x19,
	0x72, 0xb1, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0xc9, 0xea, 0x41,
	0xd5, 0xea, 0xa1, 0xa9, 0xd3, 0x0b, 0xa9, 0x2c, 0x48, 0x0d, 0x02, 0x2b, 0x15, 0xe2, 0xe3, 0x62,
	0xca, 0x4c, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe0, 0x62,
	0xce, 0x2a, 0x2f, 0x91, 0x60, 0x06, 0x0b, 0x80, 0x98, 0x42, 0x22, 0x5c, 0xac, 0xc5, 0x19, 0x99,
	0x69, 0x25, 0x12, 0x2c, 0x60, 0x31, 0x08, 0x47, 0x49, 0x98, 0x8b, 0x05, 0x64, 0x8a, 0x10, 0x37,
	0x17, 0x7b, 0xa8, 0x9f, 0xb7, 0x9f, 0x7f, 0xb8, 0x9f, 0x00, 0x43, 0x12, 0x1b, 0xd8, 0x8d, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x06, 0xaa, 0xee, 0xb5, 0x00, 0x00, 0x00,
}
