// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

/*
Package payload is a generated protocol buffer package.

It is generated from these files:
	employee.proto
	payload.proto

It has these top-level messages:
	EmployeePayload
	Payload
*/
package payload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmployeePayload_Type int32

const (
	EmployeePayload_GET_SHIFTS           EmployeePayload_Type = 0
	EmployeePayload_SHIFT_DETAILS        EmployeePayload_Type = 1
	EmployeePayload_PICK_UP_SHIFT        EmployeePayload_Type = 2
	EmployeePayload_CALL_OFF_SHIFT       EmployeePayload_Type = 3
	EmployeePayload_SHIFTS_AND_SCHEDULES EmployeePayload_Type = 4
)

var EmployeePayload_Type_name = map[int32]string{
	0: "GET_SHIFTS",
	1: "SHIFT_DETAILS",
	2: "PICK_UP_SHIFT",
	3: "CALL_OFF_SHIFT",
	4: "SHIFTS_AND_SCHEDULES",
}
var EmployeePayload_Type_value = map[string]int32{
	"GET_SHIFTS":           0,
	"SHIFT_DETAILS":        1,
	"PICK_UP_SHIFT":        2,
	"CALL_OFF_SHIFT":       3,
	"SHIFTS_AND_SCHEDULES": 4,
}

func (x EmployeePayload_Type) String() string {
	return proto.EnumName(EmployeePayload_Type_name, int32(x))
}
func (EmployeePayload_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type EmployeePayload struct {
	Type  EmployeePayload_Type `protobuf:"varint,1,opt,name=type,enum=payload.EmployeePayload_Type" json:"type,omitempty"`
	Id    string               `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Jwt   string               `protobuf:"bytes,3,opt,name=jwt" json:"jwt,omitempty"`
	Shift string               `protobuf:"bytes,4,opt,name=shift" json:"shift,omitempty"`
}

func (m *EmployeePayload) Reset()                    { *m = EmployeePayload{} }
func (m *EmployeePayload) String() string            { return proto.CompactTextString(m) }
func (*EmployeePayload) ProtoMessage()               {}
func (*EmployeePayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmployeePayload) GetType() EmployeePayload_Type {
	if m != nil {
		return m.Type
	}
	return EmployeePayload_GET_SHIFTS
}

func (m *EmployeePayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeePayload) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *EmployeePayload) GetShift() string {
	if m != nil {
		return m.Shift
	}
	return ""
}

func init() {
	proto.RegisterType((*EmployeePayload)(nil), "payload.EmployeePayload")
	proto.RegisterEnum("payload.EmployeePayload_Type", EmployeePayload_Type_name, EmployeePayload_Type_value)
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0x5b, 0x15, 0x07, 0xac, 0x71, 0xd8, 0x43, 0x2e, 0xc2, 0xb2, 0xa7, 0x3d, 0x15,
	0xd4, 0x27, 0x28, 0x6d, 0xea, 0x16, 0x83, 0x96, 0x4d, 0xf6, 0x1c, 0x56, 0x1a, 0xb1, 0xcb, 0x4a,
	0x82, 0x06, 0x24, 0x6f, 0xec, 0x63, 0xc8, 0x26, 0x3d, 0x79, 0xfb, 0xe7, 0x9b, 0x6f, 0x06, 0x7e,
	0x28, 0xcd, 0xa7, 0x3b, 0xda, 0x60, 0x4c, 0xe5, 0xbe, 0xac, 0xb7, 0x78, 0xe9, 0xf6, 0xe1, 0x68,
	0xf7, 0xe3, 0xea, 0x97, 0xc0, 0x0d, 0x9f, 0x77, 0x43, 0x62, 0x78, 0x0f, 0x85, 0x0f, 0xce, 0x30,
	0xb2, 0x24, 0xeb, 0xf2, 0xe1, 0xae, 0x9a, 0xdd, 0xea, 0x9f, 0x57, 0xa9, 0xe0, 0xcc, 0x36, 0xaa,
	0x58, 0x42, 0x36, 0x8d, 0x2c, 0x5b, 0x92, 0xf5, 0xd5, 0x36, 0x9b, 0x46, 0xa4, 0x90, 0x1f, 0x7e,
	0x3c, 0xcb, 0x23, 0x38, 0x45, 0x5c, 0xc0, 0xf9, 0xf7, 0xc7, 0xf4, 0xee, 0x59, 0x11, 0x59, 0x1a,
	0x56, 0x07, 0x28, 0x54, 0xba, 0x87, 0x27, 0xae, 0xb4, 0xdc, 0xf4, 0x9d, 0x92, 0xf4, 0x0c, 0x6f,
	0xe1, 0x3a, 0x66, 0xdd, 0x72, 0x55, 0xf7, 0x42, 0x52, 0x72, 0x42, 0x43, 0xdf, 0x3c, 0xeb, 0xdd,
	0x90, 0x34, 0x9a, 0x21, 0x42, 0xd9, 0xd4, 0x42, 0xe8, 0xd7, 0xae, 0x9b, 0x59, 0x8e, 0x0c, 0x16,
	0xe9, 0x8b, 0xae, 0x5f, 0x5a, 0x2d, 0x9b, 0x0d, 0x6f, 0x77, 0x82, 0x4b, 0x5a, 0xbc, 0x5d, 0xc4,
	0xea, 0x8f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xa4, 0x6d, 0x9e, 0x0c, 0x01, 0x00, 0x00,
}
