// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

/*
Package payload is a generated protocol buffer package.

It is generated from these files:
	payload.proto

It has these top-level messages:
	Payload
*/
package payload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload_Type int32

const (
	Payload_OPEN_SHIFTS            Payload_Type = 0
	Payload_SHIFT_DETAILS          Payload_Type = 1
	Payload_ACCEPT_SHIFT_SUBSTITUE Payload_Type = 2
	Payload_DENY_SHIFT_SUBSTITUTE  Payload_Type = 3
	Payload_FIND_SHIFT_SUBSTITUTE  Payload_Type = 4
)

var Payload_Type_name = map[int32]string{
	0: "OPEN_SHIFTS",
	1: "SHIFT_DETAILS",
	2: "ACCEPT_SHIFT_SUBSTITUE",
	3: "DENY_SHIFT_SUBSTITUTE",
	4: "FIND_SHIFT_SUBSTITUTE",
}
var Payload_Type_value = map[string]int32{
	"OPEN_SHIFTS":            0,
	"SHIFT_DETAILS":          1,
	"ACCEPT_SHIFT_SUBSTITUE": 2,
	"DENY_SHIFT_SUBSTITUTE":  3,
	"FIND_SHIFT_SUBSTITUTE":  4,
}

func (x Payload_Type) String() string {
	return proto.EnumName(Payload_Type_name, int32(x))
}
func (Payload_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Payload struct {
	Type Payload_Type `protobuf:"varint,1,opt,name=type,enum=Payload_Type" json:"type,omitempty"`
	Data string       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Payload) GetType() Payload_Type {
	if m != nil {
		return m.Type
	}
	return Payload_OPEN_SHIFTS
}

func (m *Payload) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Payload)(nil), "Payload")
	proto.RegisterEnum("Payload_Type", Payload_Type_name, Payload_Type_value)
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xac, 0xcc,
	0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xda, 0xc7, 0xc8, 0xc5, 0x1e, 0x00,
	0x11, 0x11, 0x52, 0xe4, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33,
	0xe2, 0xd5, 0x83, 0x8a, 0xeb, 0x85, 0x54, 0x16, 0xa4, 0x06, 0x81, 0xa5, 0x84, 0x84, 0xb8, 0x58,
	0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0xa5, 0x1a, 0x2e,
	0x16, 0x90, 0x0a, 0x21, 0x7e, 0x2e, 0x6e, 0xff, 0x00, 0x57, 0xbf, 0xf8, 0x60, 0x0f, 0x4f, 0xb7,
	0x90, 0x60, 0x01, 0x06, 0x21, 0x41, 0x2e, 0x5e, 0x30, 0x3b, 0xde, 0xc5, 0x35, 0xc4, 0xd1, 0xd3,
	0x27, 0x58, 0x80, 0x51, 0x48, 0x8a, 0x4b, 0xcc, 0xd1, 0xd9, 0xd9, 0x35, 0x20, 0x04, 0xa2, 0x2a,
	0x3e, 0x38, 0xd4, 0x29, 0x38, 0xc4, 0x33, 0x24, 0xd4, 0x55, 0x80, 0x49, 0x48, 0x92, 0x4b, 0xd4,
	0xc5, 0xd5, 0x2f, 0x12, 0x4d, 0x26, 0xc4, 0x55, 0x80, 0x19, 0x24, 0xe5, 0xe6, 0xe9, 0xe7, 0x82,
	0x29, 0xc5, 0x92, 0xc4, 0x06, 0xf6, 0x87, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xb1, 0x5a,
	0x61, 0xd8, 0x00, 0x00, 0x00,
}
